### ISSUE TITLE
Connect to trackers

### ISSUE THREAD

**Issue by bpogodzinski** [Lamprey-BitTorrent/lamprey-cli#4]
Add class `Tracker` that will have a method that connects to some example tracker and get data from it. Find some example tracker links to try. Example code:
```python
import requests as r
class Tracker:
# class fields

  def connect(self, parameters):
    link = get_link(params)
    data = r.get(link)
    return data
```
You can create your own `dataclasses` and return them instead of raw data.

**Comment by PrzybyszB** [comment]
https://wiki.theory.org/BitTorrentSpecification#Info_Dictionary

There are information about our info to hash
